"""empty message

Revision ID: bbff1c6733ca
Revises: fead6d1028b2
Create Date: 2024-04-30 13:17:47.184164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbff1c6733ca'
down_revision = 'fead6d1028b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothing', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
