"""empty message

Revision ID: 63f3191df740
Revises: c95c908ec2e3
Create Date: 2024-05-05 21:17:00.285401

"""
from alembic import op
import sqlalchemy as sa
import os

# revision identifiers, used by Alembic.
revision = '63f3191df740'
down_revision = 'c95c908ec2e3'
branch_labels = None
depends_on = None

# Environment variable to determine the schema
environment = os.getenv("FLASK_ENV")
SCHEMA = os.getenv("SCHEMA")

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema_to_use = SCHEMA if environment == "production" else None
    with op.batch_alter_table('clothing', schema=schema_to_use) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    schema_to_use = SCHEMA if environment == "production" else None
    with op.batch_alter_table('clothing', schema=schema_to_use) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
