"""empty message

Revision ID: 97c72d9152b1
Revises:
Create Date: 2024-05-05 22:03:02.713184

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '97c72d9152b1'
down_revision = None
branch_labels = None
depends_on = None


def table_name(name):
    """Prepends a schema name to tables if in production environment."""
    return f"{SCHEMA}.{name}" if environment == "production" and SCHEMA else name

def upgrade():
    # Commands auto-generated by Alembic - please adjust!
    if environment == "production" and SCHEMA:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema=SCHEMA if environment == "production" else None
    )

    op.create_table('clothing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('images', sa.String(length=255), nullable=True),
    sa.Column('date_listed', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [table_name('users.id')]),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA if environment == "production" else None
    )
    # Create other tables following the same pattern
    # ### end Alembic commands ###

def downgrade():
    # Commands auto-generated by Alembic - please adjust!
    op.drop_table('wishlist_item', schema=SCHEMA if environment == "production" else None)
    op.drop_table('reviews', schema=SCHEMA if environment == "production" else None)
    op.drop_table('offers', schema=SCHEMA if environment == "production" else None)
    op.drop_table('wishlist', schema=SCHEMA if environment == "production" else None)
    op.drop_table('clothing', schema=SCHEMA if environment == "production" else None)
    op.drop_table('users', schema=SCHEMA if environment == "production" else None)
    # ### end Alembic commands ###
