"""empty message

Revision ID: c95c908ec2e3
Revises:
Create Date: 2024-04-30 17:58:27.923076

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'c95c908ec2e3'
down_revision = None
branch_labels = None
depends_on = None

def table_schema(table_name):
    return f"{SCHEMA}.{table_name}" if environment == "production" and SCHEMA else table_name

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    if environment == "production" and SCHEMA:
        connection.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema=SCHEMA if environment == "production" else None
    )
    op.create_table('clothing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('images', sa.String(length=255), nullable=True),
    sa.Column('date_listed', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [table_schema('users.id')]),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA if environment == "production" else None
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [table_schema('users.id')]),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA if environment == "production" else None
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clothing_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('offer_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_details', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], [table_schema('clothing.id')], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], [table_schema('users.id')]),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA if environment == "production" else None
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewee_id', sa.Integer(), nullable=False),
    sa.Column('clothing_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clothing_id'], [table_schema('clothing.id')]),
    sa.ForeignKeyConstraint(['reviewee_id'], [table_schema('users.id')]),
    sa.ForeignKeyConstraint(['reviewer_id'], [table_schema('users.id')]),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA if environment == "production" else None
    )
    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('clothing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clothing_id'], [table_schema('clothing.id')]),
    sa.ForeignKeyConstraint(['wishlist_id'], [table_schema('wishlist.id')]),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA if environment == "production" else None
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    op.drop_table('wishlist_item', schema=SCHEMA if environment == "production" else None)
    op.drop_table('reviews', schema=SCHEMA if environment == "production" else None)
    op.drop_table('offers', schema=SCHEMA if environment == "production" else None)
    op.drop_table('wishlist', schema=SCHEMA if environment == "production" else None)
    op.drop_table('clothing', schema=SCHEMA if environment == "production" else None)
    op.drop_table('users', schema=SCHEMA if environment == "production" else None)
    # ### end Alembic commands ###
